# Generated by Django 3.1 on 2020-10-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_outdoor_engineer',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as an Outdoor Engineer. ', verbose_name='outdoor engineer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'engineer'), (3, 'customer'), (4, 'outdoor_engineer')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
