# Generated by Django 3.1 on 2020-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20201029_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['title'], 'verbose_name': 'العمل ', 'verbose_name_plural': 'الأعمال '},
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
    ]
